server:
  port: 8081

#配置日志级别
logging:
  level:
    root: debug

#dubbo配置
spring:
  dubbo:
    application: manage-web
    #dubbo通讯协议名称
    protocol:
      name: dubbo
      port: 208081

    registry:
      #zookeeper注册中心地址
      address: 49.235.125.139:2181
      #zookeeper的通讯协议名称
      protocol: zookeeper
    #dubbo的扫描路径
    base-package: com.ygl.gmall

    consumer:
      #设置超时时间  十分钟
      timeout: 600000
      #设置是否检查服务存在
      check: false

