
server:
  port: 8181


spring:
  #redis配置
  redis:
    host: 192.168.80.133
    port: 6379
    database: 0
  #jdbc配置
  datasource:
    username: root
    password: 123456
    url:  jdbc:mysql://127.0.0.1:3306/gmall_study?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #dubbo的配置
  dubbo:
    #dubbo服务名称
    application: redission-test
    registry:
      #zookeeper注册中心地址
      address: 192.168.80.133:2181
      #zookeeper的通讯协议的名称
      protocol: zookeeper
    #dubbo的通讯协议名称
    protocol:
      name: dubbo
    #dubbo的服务扫描路径
    base-package: com.ygl.gmall


#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  #数据库下划线转成驼峰
  configuration:
    map-underscore-to-camel-case: true


#日志打印级别
#logging:
#  level:
#    root: debug
